---
abstract: 'Conjure up a usage function for your applications'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  File::Spec: 0
  IPC::Open3: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Usaginator
recommends: {}
requires:
  Package::Pkg: 0.0014
version: 0.0012
